services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://laravel-api-zg6b.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d23k49u3jp1c73a0jg70-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: mobile_shop_db
      - key: DB_USERNAME
        value: mobile_shop_db_user
      - key: DB_PASSWORD
        value: RhANGuVrCNdqPIGoZh20nKR5LrrTpdcT
